/**
 * Error codes — machine-readable, surfaced in OpenAPI, used by the FE to branch on `code`.
 * Rules: append-only, never reuse or renumber a deleted code, RESOURCE_REASON convention.
 */

export const ErrorCodes = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  RATE_LIMITED: 'RATE_LIMITED',
  INVALID_CURSOR: 'INVALID_CURSOR',
  INVALID_FILTER: 'INVALID_FILTER',

  // Auth / Identity
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_SESSION_REVOKED: 'AUTH_SESSION_REVOKED',
  AUTH_REFRESH_TOKEN_REUSE: 'AUTH_REFRESH_TOKEN_REUSE',
  AUTH_MFA_REQUIRED: 'AUTH_MFA_REQUIRED',

  // Tenant / Workspace
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  TENANT_SUSPENDED: 'TENANT_SUSPENDED',
  TENANT_SLUG_TAKEN: 'TENANT_SLUG_TAKEN',
  WORKSPACE_NOT_FOUND: 'WORKSPACE_NOT_FOUND',
  WORKSPACE_SLUG_TAKEN: 'WORKSPACE_SLUG_TAKEN',
  WORKSPACE_MEMBER_NOT_FOUND: 'WORKSPACE_MEMBER_NOT_FOUND',
  WORKSPACE_MEMBER_ALREADY_EXISTS: 'WORKSPACE_MEMBER_ALREADY_EXISTS',

  // Project
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_KEY_TAKEN: 'PROJECT_KEY_TAKEN',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',
  LABEL_NOT_FOUND: 'LABEL_NOT_FOUND',

  // Work item
  WORK_ITEM_NOT_FOUND: 'WORK_ITEM_NOT_FOUND',
  WORK_ITEM_RANK_CONFLICT: 'WORK_ITEM_RANK_CONFLICT',
  WORK_ITEM_INVALID_TRANSITION: 'WORK_ITEM_INVALID_TRANSITION',
  WORK_ITEM_INVALID_PARENT_TYPE: 'WORK_ITEM_INVALID_PARENT_TYPE',
  WORK_ITEM_CIRCULAR_PARENT: 'WORK_ITEM_CIRCULAR_PARENT',
  WORK_ITEM_MAX_DEPTH_EXCEEDED: 'WORK_ITEM_MAX_DEPTH_EXCEEDED',

  // Workflow
  WORKFLOW_STATUS_NOT_FOUND: 'WORKFLOW_STATUS_NOT_FOUND',
  WORKFLOW_TRANSITION_NOT_ALLOWED: 'WORKFLOW_TRANSITION_NOT_ALLOWED',

  // Sprint / Planning
  SPRINT_NOT_FOUND: 'SPRINT_NOT_FOUND',
  SPRINT_ALREADY_ACTIVE: 'SPRINT_ALREADY_ACTIVE',
  SPRINT_PROJECT_MISMATCH: 'SPRINT_PROJECT_MISMATCH',

  // Release
  RELEASE_NOT_FOUND: 'RELEASE_NOT_FOUND',

  // Access / Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',
  ROLE_ASSIGNMENT_NOT_FOUND: 'ROLE_ASSIGNMENT_NOT_FOUND',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_DEACTIVATED: 'USER_DEACTIVATED',

  // Password reset
  PASSWORD_RESET_TOKEN_INVALID: 'PASSWORD_RESET_TOKEN_INVALID',
  PASSWORD_RESET_TOKEN_EXPIRED: 'PASSWORD_RESET_TOKEN_EXPIRED',

  // Workspace invitations
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_NOT_PENDING: 'INVITATION_NOT_PENDING',
  INVITATION_ALREADY_USED: 'INVITATION_ALREADY_USED',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  SOLE_ADMIN_VIOLATION: 'SOLE_ADMIN_VIOLATION',

  // Teams
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  TEAM_KEY_TAKEN: 'TEAM_KEY_TAKEN',
  TEAM_ALREADY_ARCHIVED: 'TEAM_ALREADY_ARCHIVED',
  TEAM_MEMBER_NOT_FOUND: 'TEAM_MEMBER_NOT_FOUND',
  TEAM_MEMBER_ALREADY_EXISTS: 'TEAM_MEMBER_ALREADY_EXISTS',

  // Project teams / members
  PROJECT_TEAM_ALREADY_LINKED: 'PROJECT_TEAM_ALREADY_LINKED',
  PROJECT_TEAM_LINK_NOT_FOUND: 'PROJECT_TEAM_LINK_NOT_FOUND',
  PROJECT_MEMBER_NOT_FOUND: 'PROJECT_MEMBER_NOT_FOUND',
  PROJECT_MEMBER_ALREADY_EXISTS: 'PROJECT_MEMBER_ALREADY_EXISTS',

  // Collaboration
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
  ATTACHMENT_NOT_FOUND: 'ATTACHMENT_NOT_FOUND',
  COMMENT_NOT_OWNED: 'COMMENT_NOT_OWNED',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',

  // Audit
  AUDIT_LOG_NOT_FOUND: 'AUDIT_LOG_NOT_FOUND',

  // Reporting
  REPORT_INVALID_DATE_RANGE: 'REPORT_INVALID_DATE_RANGE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export type ErrorCategory =
  | 'NOT_FOUND'
  | 'CONFLICT'
  | 'VALIDATION_FAILED'
  | 'PERMISSION_DENIED'
  | 'PRECONDITION_FAILED'
  | 'RATE_LIMITED'
  | 'UNAUTHORIZED'
  | 'INTERNAL';

export const CATEGORY_HTTP_STATUS: Record<ErrorCategory, number> = {
  NOT_FOUND: 404,
  CONFLICT: 409,
  VALIDATION_FAILED: 422,
  PERMISSION_DENIED: 403,
  PRECONDITION_FAILED: 400,
  RATE_LIMITED: 429,
  UNAUTHORIZED: 401,
  INTERNAL: 500,
};
